# =============================================================================
# Estándares de Arquitectura/catalog-info.yaml
# =============================================================================

# -----------------------------------------------------------------------------
# 1. DOMAIN - Dominio de negocio: Gobierno de Arquitectura Corporativa y TI
# -----------------------------------------------------------------------------
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: estandares-arquitectura
  title: Estándares de Arquitectura
  description: >
    Documentación de estándares de arquitectura
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - estandares
    - arquitectura
    - desarrollo
    - seguridad
    - operaciones


spec:
  type: documentation
  lifecycle: production
  owner: platform-team
  providesApis:
    - ejemplo-openapi
    - ejemplo-asyncapi

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ejemplo-openapi
  description: API REST para gestión de documentos
  tags: [rest, openapi]
  annotations:
   backstage.io/techdocs-entity: component:default/estandares-arquitectura
spec:
  type: openapi
  lifecycle: production
  owner: platform-team
  definition:
    $text: ./openapi.yaml

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ejemplo-asyncapi
  description: Contrato de eventos asíncronos
  tags: [amqp, openapi]
  annotations:
   backstage.io/techdocs-entity: component:default/estandares-arquitectura
spec:
  type: asyncapi
  lifecycle: production
  owner: platform-team
  definition:
    $text: ./asyncapi.yaml

