apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: estandares-arquitectura
  title: Estándares de Arquitectura
  description: >
    Documentación oficial de estándares de arquitectura, desarrollo, seguridad
    y operaciones. 
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - estandares
    - arquitectura
    - desarrollo
    - seguridad
    - operaciones
    - ingenieria

spec:
  type: documentation
  lifecycle: produccion
  owner: group:team-arq
  providesApis:
    - ejemplo-rest-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ejemplo-rest-api
  description: API REST para gestión de documentos
  tags: [rest, openapi]
  annotations:
   backstage.io/techdocs-entity: component:/docs/default/component/estandares-arquitectura/desarrollo/estandares-apis/
spec:
  type: openapi
  lifecycle: production
  owner: group:team-arq
  definition:
    $text: ./openapi.yaml
